"""empty message

Revision ID: adba8393112
Revises: None
Create Date: 2015-04-20 16:18:28.220695

"""

# revision identifiers, used by Alembic.
revision = 'adba8393112'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domains', sa.UnicodeText(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('crawl_started', sa.DateTime(), nullable=True),
    sa.Column('crawl_ended', sa.DateTime(), nullable=True),
    sa.Column('crawl_status', sa.String(length=256), nullable=False),
    sa.Column('sitemap', sa.UnicodeText(length=2147483648), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitemap_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitemap_id', sa.Integer(), nullable=True),
    sa.Column('error_name', sa.UnicodeText(length=1024), nullable=False),
    sa.Column('error_details', sa.UnicodeText(length=2147483648), nullable=True),
    sa.ForeignKeyConstraint(['sitemap_id'], ['sitemap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap_error')
    op.drop_table('sitemap')
    ### end Alembic commands ###
